## COPY: Tragedias y desgracias 

Supongamos partimos de un arreglo original del cual extraemos los ultimos 5 datos en otro arreglo, sobre el cual hacemos unas modificiaciones.

Sin embargo, cuando veamos el contenido del arreglo original, observaremos se habra perdido informacion de forma inexplicable. ¿Porque y como evitarlo?

Esto pasa haci los dos objetos sean diferentes en memoria

In [27]:
import numpy as np

original = np.arange(0,20,2)
print('arreglo original: ', original)

trozo_original = original[-5:]
print('trozo del original: ',trozo_original)

# Asignamos ceros a todo el arreglo
trozo_original[:] = 0 

print('')
print('arreglo original:' , original)

id(trozo_original) == id(original)

arreglo original:  [ 0  2  4  6  8 10 12 14 16 18]
trozo del original:  [10 12 14 16 18]

arreglo original: [0 2 4 6 8 0 0 0 0 0]


False

¿Terrible bug?

Esto pasa en *numpy* y en muchas de las estructuras en Python. En un principio ese *trozo* se definio en base al original

    trozo_original = original[-5:]

Sin embargo cuando se asignan ceros, Python me dice que si bien yo como programador lo queria manejar por aparte, sigue haciendo referencia al objeto en memoria del arreglo original

Cualquier cambio que ocurra va a afectar al objeto padre, por decirlo de alguna manera

Para solucionarlo, usamos el metodo *copy*. Veamos el codigo corregido

In [28]:
original = np.arange(0,20,2)

trozo_original = original.copy()
trozo_original = trozo_original[-5:]
print('trozo del original: ',trozo_original)

# Asignamos ceros a todo el arreglo
trozo_original[:] = 0 

print('')
print('arreglo original:' , original)

trozo del original:  [10 12 14 16 18]

arreglo original: [ 0  2  4  6  8 10 12 14 16 18]


### Listas en Python

El bug que acabamos de ver con los arreglos de numpy, nos recuerda al mismo que tenemos con las listas en Python. Hechemos un recorderis.

Creemos una lista original, y  hagamos una copia. Sin embargo, si hacemos una modificacion en la lista original, esta se var a ver reflejada tambien la copia, porque las dos listas hacen referencia al mismo espacio en memoria. 

In [25]:
my_list = [ ((-1)**i)*i for i in range(10)]
print('lista original:', my_list)

new_list = my_list

my_list.append(-100)

print('lista original modificada',my_list)
print('nueva lista', new_list)

id(my_list)==id(new_list)

lista original: [0, -1, 2, -3, 4, -5, 6, -7, 8, -9]
lista original modificada [0, -1, 2, -3, 4, -5, 6, -7, 8, -9, -100]
nueva lista [0, -1, 2, -3, 4, -5, 6, -7, 8, -9, -100]


True

#### Conclusion

Ten mucho cuidado al sacar partes o trozos de un tensor o un arreglo en numpy. Lo mejor es usar el metodo *copy* y a partir de ahi hacer nuestras modificaciones.

Tambien que se puede copiar el arreglo, y al mimso tiempo hacer el slicing, veamos:

In [35]:
my_array = [ ((-1)**i)*i for i in range(10)]
my_array = np.array(my_array)

my_copy = my_array.copy()[-5:]
print(my_copy)

[-5  6 -7  8 -9]


## Condiciones

Ya sabemos hacer indexing, slicing, ¿Pero que si nos gustaria retornar solo los numeros del arreglo que cumplan con una condicion?

Por ejemplo los numeros mayores o iguales que cero

In [42]:
import numpy as np

my_array = [ ((-1)**i)*i**2 for i in range(10)]
my_array = np.array(my_array, dtype='int8')

print('my_array =', my_array)

my_array = [  0  -1   4  -9  16 -25  36 -49  64 -81]


In [45]:
my_array >=0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

Si aplicamos una condicional tal y como lo acabamos de hacer, nos retornara una lista booleana con los elementos que cumplen esa condicion.

Pero ahora, extraigamos los valores que cumplen con la condicion.

In [46]:
condicion = my_array >=0

my_array[condicion]

array([ 0,  4, 16, 36, 64], dtype=int8)

Que tal si lo hacemos mas complejo: los que son mayores o iguales que cero y multiplos de 16

In [55]:
my_array[(my_array >=0) & (my_array%16 ==0)] 

array([ 0, 16, 64], dtype=int8)

Y asignarlo a un nuevo arreglo

In [59]:
new_array = my_array[(my_array >=0) & (my_array%16 ==0)] 
print(new_array)

[ 0 16 64]


### ejemplo

Los valores que cumplan con la condicion, de ser multiplos de 3, intercambirarlos por 127. Tener en cuenta que el tipo de dato **int8** solo soporta enteros positivos hasta el 127. Por eso cuando le daba 1000, no funcionaba, y creaba un bug

In [14]:
import numpy as np

my_array = [ ((-1)**i)*i**2 for i in range(10)]
my_array = np.array(my_array, dtype='int8')

print('my_array =', my_array)

my_array[my_array%3 == 0] = 127

print(my_array)

my_array[my_array==127]


my_array = [  0  -1   4  -9  16 -25  36 -49  64 -81]
[127  -1   4 127  16 -25 127 -49  64 127]


array([127, 127, 127, 127], dtype=int8)

## Operaciones

Existen diferentes operaciones que se pueden usar para los arrays de NumPy.

- Multipliciacion/Division de todos los valores por un escalar
- Suma y resta de los elementos por un escalar
- Dividir un escalar entre el mismo arreglo. 

#### Ejemplo

Crear una lista de 10 elementos, y copiar mediante el metodo copy en una lista los ultimos 4 elemento

In [18]:
import numpy as np

my_array = np.arange(10)
my_array_1 = my_array.copy()[-4:] 
print(my_array_1)

[6 7 8 9]


In [19]:
(my_array_1 * 2) - 1

array([11, 13, 15, 17])

In [20]:
my_array_1/10

array([0.6, 0.7, 0.8, 0.9])

In [21]:
1/my_array_1

array([0.16666667, 0.14285714, 0.125     , 0.11111111])

Notar que si llega haber division por cer, no dejara de ejecutar la ejecucion, pero mostrara una excepcion cuando esto ocurra para el elemento en particular

In [22]:
my_array_1 = my_array.copy()[:4]
1/my_array_1


/tmp/ipykernel_275/545081694.py:2: RuntimeWarning: divide by zero encountered in divide
  1/my_array_1


array([       inf, 1.        , 0.5       , 0.33333333])

### Dado el caso que sea una matriz, tambien se pueden realizar operaciones

Creemos dos matrices de enteros aleatorios

In [47]:
matriz = np.random.randint(0,5,(2,3))
matriz1 = np.random.randint(0,5,(2,3))
print(matriz)
print('')
print(matriz1)

[[1 2 1]
 [0 3 2]]

[[4 2 2]
 [4 4 2]]


In [49]:
matriz1 - 2*matriz

array([[ 2, -2,  0],
       [ 4, -2, -2]])

*matmul* nos devuelve el producto punto entre matrices, tal y como lo hacemos en algebra lineal. Recuerda tambien puedes usar una @

In [50]:
np.matmul(matriz,matriz1.T)

array([[10, 14],
       [10, 16]])

In [51]:
matriz.dot(matriz1.T)

array([[10, 14],
       [10, 16]])

In [52]:
matriz @ matriz1.T

array([[10, 14],
       [10, 16]])

#### Otra operacion super interesante

¿Te has preguntado si es posible quitar los valores repetidos en un array, y ademas saber su frecuencia relativa?

In [59]:
my_array = np.random.randint(-3,3,(50))
print(my_array)

[-3 -2 -2  0  2  2 -3 -3 -2 -1 -1  2  2  2 -3  0  1 -1  0  1  1  0  2 -3
  0  0 -2 -2  1  2  1 -3  0  0  2  1 -1 -3  1 -2  1 -2 -3  0  1  0 -2  0
 -2 -2]


In [60]:
unique = np.unique(my_array)
print(unique)

[-3 -2 -1  0  1  2]


In [61]:
unique, occurrence = np.unique(my_array, return_counts=True)
print(occurrence)

[ 8 10  4 11  9  8]
